In [1]:
import pandas as pd

In [2]:
data_path = '../../datasets/premier/{season}.csv'
# we will use the same dataframes for all the seasons
dfs = {}

for season in range(15, 26):
    dfs[season] = pd.read_csv(data_path.format(season=season))

# concatenate all the dataframes
df = pd.concat(dfs.values(), ignore_index=True, axis=0)

In [3]:
# get info about the dataframe
df.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
count,4051.000000,4051.000000,4051.000000,4051.000000,4051.000000,4051.000000,4051.000000,4051.000000,4051.000000,4051.000000,...,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000
mean,1.550975,1.269810,0.703777,0.565539,14.060726,11.495927,4.802024,4.003456,10.601086,10.941002,...,2.902988,4.465896,4.478167,2.975498,4.605578,4.988287,1.692072,2.592311,1.984064,2.005339
std,1.315456,1.205758,0.855849,0.774812,5.731289,4.972534,2.638613,2.340937,3.450438,3.597355,...,1.843139,1.441771,3.764786,1.999587,1.539490,4.839703,0.233830,0.577645,0.086867,0.087701
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,...,1.080000,3.160000,1.300000,1.100000,3.200000,1.290000,1.210000,1.610000,1.750000,1.810000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,8.000000,3.000000,2.000000,8.000000,8.000000,...,1.655000,3.670000,2.130000,1.670000,3.750000,2.250000,1.520000,2.160000,1.920000,1.940000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,11.000000,5.000000,4.000000,10.000000,11.000000,...,2.270000,4.000000,3.260000,2.300000,4.100000,3.350000,1.670000,2.460000,1.970000,2.010000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,15.000000,6.000000,5.000000,13.000000,13.000000,...,3.440000,4.830000,5.365000,3.525000,5.000000,5.650000,1.850000,2.900000,2.050000,2.070000
max,9.000000,9.000000,5.000000,5.000000,43.000000,37.000000,17.000000,15.000000,24.000000,25.000000,...,9.700000,14.700000,28.000000,11.500000,15.000000,32.000000,2.600000,5.500000,2.210000,2.300000

In [4]:
df.columns.to_list()

['Div',
 'Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'SJH',
 'SJD',
 'SJA',
 'VCH',
 'VCD',
 'VCA',
 'Bb1X2',
 'BbMxH',
 'BbAvH',
 'BbMxD',
 'BbAvD',
 'BbMxA',
 'BbAvA',
 'BbOU',
 'BbMx>2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'BbAv<2.5',
 'BbAH',
 'BbAHh',
 'BbMxAHH',
 'BbAvAHH',
 'BbMxAHA',
 'BbAvAHA',
 'PSCH',
 'PSCD',
 'PSCA',
 'Time',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFH',
 'BFD',
 'BFA',
 '1XBH',
 '1XBD',
 '1XBA',
 'BFEH',
 'BFED',
 'BFEA',
 'BFE>2.5',
 'BFE<2.5',
 'BFEAHH',
 'BFEAHA',
 'BFCH',
 'BFCD',
 'BFCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'BFEC>2.5',
 'BFEC<2.5',
 'BFECAHH',
 'BFECAHA']

In [5]:
# get the 40 columns with the most non-null values
df.count().nlargest(50)

Div         4051
Date        4051
HomeTeam    4051
AwayTeam    4051
FTHG        4051
FTAG        4051
FTR         4051
HTHG        4051
HTAG        4051
HTR         4051
Referee     4051
HS          4051
AS          4051
HST         4051
AST         4051
HF          4051
AF          4051
HC          4051
AC          4051
HY          4051
AY          4051
HR          4051
AR          4051
B365H       4051
B365D       4051
B365A       4051
PSH         4051
PSD         4051
PSA         4051
WHH         4051
WHD         4051
WHA         4051
PSCH        4051
PSCD        4051
PSCA        4051
BWH         4036
BWD         4036
BWA         4036
VCH         3800
VCD         3800
VCA         3800
IWH         3617
IWD         3617
IWA         3617
Time        2151
MaxH        2151
MaxD        2151
MaxA        2151
AvgH        2151
AvgD        2151
dtype: int64

In [6]:
reduced_df = df[[
'FTHG',
'FTAG',
'HTHG',
'HTAG',
'HS',
'AS',
'HST',
'AST',
'HF',
'AF',
'HC',
'AC',
'HY',
'AY',
'HR',
'AR', 
'MaxH', 
'MaxD', 
'MaxA', 
'AvgH', 
'AvgD', 
'AvgA',
'B365H',
'B365D',
'B365A',
'BFH',
'BFD',
'BFA',
'PSH',
'PSD',
'PSA',
'WHH',
'WHD',
'WHA',
'Max>2.5',
'Max<2.5',
'Avg>2.5',
'Avg<2.5',
'AHh',
'B365AHH',
'B365AHA',
'PAHH',
'PAHA',
'MaxAHH',
'MaxAHA',
]]

In [7]:
reduced_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4052 entries, 0 to 4051
Data columns (total 45 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   FTHG     4051 non-null   float64
 1   FTAG     4051 non-null   float64
 2   HTHG     4051 non-null   float64
 3   HTAG     4051 non-null   float64
 4   HS       4051 non-null   float64
 5   AS       4051 non-null   float64
 6   HST      4051 non-null   float64
 7   AST      4051 non-null   float64
 8   HF       4051 non-null   float64
 9   AF       4051 non-null   float64
 10  HC       4051 non-null   float64
 11  AC       4051 non-null   float64
 12  HY       4051 non-null   float64
 13  AY       4051 non-null   float64
 14  HR       4051 non-null   float64
 15  AR       4051 non-null   float64
 16  MaxH     2151 non-null   float64
 17  MaxD     2151 non-null   float64
 18  MaxA     2151 non-null   float64
 19  AvgH     2151 non-null   float64
 20  AvgD     2151 non-null   float64
 21  AvgA     2151 non-null   float64
 22  B365H    4051 non-null   float64
 23  B365D    4051 non-null   float64
 24  B365A    4051 non-null   float64
 25  BFH      250 non-null    float64
 26  BFD      250 non-null    float64
 27  BFA      250 non-null    float64
 28  PSH      4051 non-null   float64
 29  PSD      4051 non-null   float64
 30  PSA      4051 non-null   float64
 31  WHH      4051 non-null   float64
 32  WHD      4051 non-null   float64
 33  WHA      4051 non-null   float64
 34  Max>2.5  2151 non-null   float64
 35  Max<2.5  2151 non-null   float64
 36  Avg>2.5  2151 non-null   float64
 37  Avg<2.5  2151 non-null   float64
 38  AHh      2151 non-null   float64
 39  B365AHH  2151 non-null   float64
 40  B365AHA  2151 non-null   float64
 41  PAHH     2151 non-null   float64
 42  PAHA     2151 non-null   float64
 43  MaxAHH   2151 non-null   float64
 44  MaxAHA   2151 non-null   float64
dtypes: float64(45)
memory usage: 1.4 MB