In [1]:
import pandas as pd

In [5]:
data_path = '../../datasets/premier/{season}.csv'
# we will use the same dataframes for all the seasons
dfs = {}

for season in range(20, 26):
    dfs[season] = pd.read_csv(data_path.format(season=season))

# concatenate all the dataframes
df = pd.concat(dfs.values(), ignore_index=True, axis=0)

In [9]:
# get info about the dataframe
df.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
count,2151.000000,2151.000000,2151.000000,2151.000000,2151.000000,2151.000000,2151.000000,2151.000000,2151.000000,2151.000000,...,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000
mean,1.560669,1.330079,0.713157,0.592748,13.894468,11.681543,4.852627,4.134356,10.660158,10.857741,...,2.902988,4.465896,4.478167,2.975498,4.605578,4.988287,1.692072,2.592311,1.984064,2.005339
std,1.337097,1.239963,0.860508,0.800362,5.738529,5.208975,2.627607,2.424120,3.489957,3.639606,...,1.843139,1.441771,3.764786,1.999587,1.539490,4.839703,0.233830,0.577645,0.086867,0.087701
min,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,...,1.080000,3.160000,1.300000,1.100000,3.200000,1.290000,1.210000,1.610000,1.750000,1.810000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,8.000000,3.000000,2.000000,8.000000,8.000000,...,1.655000,3.670000,2.130000,1.670000,3.750000,2.250000,1.520000,2.160000,1.920000,1.940000
50%,1.000000,1.000000,1.000000,0.000000,13.000000,11.000000,5.000000,4.000000,10.000000,11.000000,...,2.270000,4.000000,3.260000,2.300000,4.100000,3.350000,1.670000,2.460000,1.970000,2.010000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,15.000000,6.000000,6.000000,13.000000,13.000000,...,3.440000,4.830000,5.365000,3.525000,5.000000,5.650000,1.850000,2.900000,2.050000,2.070000
max,9.000000,9.000000,5.000000,5.000000,36.000000,37.000000,16.000000,15.000000,23.000000,25.000000,...,9.700000,14.700000,28.000000,11.500000,15.000000,32.000000,2.600000,5.500000,2.210000,2.300000

In [11]:
df.columns.to_list()

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFH',
 'BFD',
 'BFA',
 '1XBH',
 '1XBD',
 '1XBA',
 'BFEH',
 'BFED',
 'BFEA',
 'BFE>2.5',
 'BFE<2.5',
 'BFEAHH',
 'BFEAHA',
 'BFCH',
 'BFCD',
 'BFCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'BFEC>2.5',
 'BFEC<2.5',
 'BFECAHH',
 'BFECAHA']

In [22]:
# get the 40 columns with the most non-null values
df.count().nlargest(40)

Div         2151
Date        2151
Time        2151
HomeTeam    2151
AwayTeam    2151
FTHG        2151
FTAG        2151
FTR         2151
HTHG        2151
HTAG        2151
HTR         2151
Referee     2151
HS          2151
AS          2151
HST         2151
AST         2151
HF          2151
AF          2151
HC          2151
AC          2151
HY          2151
AY          2151
HR          2151
AR          2151
B365H       2151
B365D       2151
B365A       2151
PSH         2151
PSD         2151
PSA         2151
WHH         2151
WHD         2151
WHA         2151
MaxH        2151
MaxD        2151
MaxA        2151
AvgH        2151
AvgD        2151
AvgA        2151
Max>2.5     2151
dtype: int64

In [23]:
reduced_df = df[[
'FTHG',
'FTAG',
'HTHG',
'HTAG',
'HS',
'AS',
'HST',
'AST',
'HF',
'AF',
'HC',
'AC',
'HY',
'AY',
'HR',
'AR', 
'MaxH', 
'MaxD', 
'MaxA', 
'AvgH', 
'AvgD', 
'AvgA',
'B365H',
'B365D',
'B365A',
'BFH',
'BFD',
'BFA',
'PSH',
'PSD',
'PSA',
]]

In [25]:
reduced_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2151 entries, 0 to 2150
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   FTHG    2151 non-null   int64
 1   FTAG    2151 non-null   int64
 2   HTHG    2151 non-null   int64
 3   HTAG    2151 non-null   int64
 4   HS      2151 non-null   int64
 5   AS      2151 non-null   int64
 6   HST     2151 non-null   int64
 7   AST     2151 non-null   int64
 8   HF      2151 non-null   int64
 9   AF      2151 non-null   int64
 10  HC      2151 non-null   int64
 11  AC      2151 non-null   int64
 12  HY      2151 non-null   int64
 13  AY      2151 non-null   int64
 14  HR      2151 non-null   int64
 15  AR      2151 non-null   int64
 16  MaxH    2151 non-null   float64
 17  MaxD    2151 non-null   float64
 18  MaxA    2151 non-null   float64
 19  AvgH    2151 non-null   float64
 20  AvgD    2151 non-null   float64
 21  AvgA    2151 non-null   float64
 22  B365H   2151 non-null   float64
 23  B365D   2151 non-null   float64
 24  B365A   2151 non-null   float64
 25  BFH     250 non-null    float64
 26  BFD     250 non-null    float64
 27  BFA     250 non-null    float64
 28  PSH     2151 non-null   float64
 29  PSD     2151 non-null   float64
 30  PSA     2151 non-null   float64
dtypes: float64(15), int64(16)
memory usage: 521.1 KB